version: '3'

services:
  # Web server service
  www:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"  # Mount local directory into container
    ports:
      - "9000:80"  # Map container port 80 to host port 9000

  # MySQL database service
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=students_database
      - MYSQL_USER=hamza12
      - MYSQL_PASSWORD=wh123
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"  # Mount database initialization scripts

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports: 
      - "9001:80"  # Map container port 80 to host port 9001
    environment:
      - PMA_HOST=db  # Set phpMyAdmin host to the database service
      - PMA_PORT=3306  # Set phpMyAdmin port to MySQL port
    depends_on:
      - db  # Ensure that the phpMyAdmin service starts after the db service
